create table if not exists public.learning_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id text not null check (char_length(video_id) = 11),
  video_title text,
  channel_name text,
  duration_sec double precision not null default 0 check (duration_sec >= 0),
  last_position_sec double precision not null default 0 check (last_position_sec >= 0),
  progress_percent numeric(5, 2) not null default 0 check (progress_percent between 0 and 100),
  status text not null default 'started' check (status in ('started', 'in_progress', 'completed')),
  started_at timestamptz not null default now(),
  last_studied_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (user_id, video_id)
);

create index if not exists learning_progress_user_recent_idx
  on public.learning_progress (user_id, last_studied_at desc);

alter table public.learning_progress enable row level security;

revoke all on table public.learning_progress from anon;
grant select, insert, update, delete on table public.learning_progress to authenticated;
grant usage, select on sequence public.learning_progress_id_seq to authenticated;

create policy "Users can read their learning progress"
  on public.learning_progress for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their learning progress"
  on public.learning_progress for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their learning progress"
  on public.learning_progress for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their learning progress"
  on public.learning_progress for delete
  to authenticated
  using ((select auth.uid()) = user_id);
