create table if not exists public.saved_words (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null check (char_length(word) between 1 and 120),
  word_key text not null check (char_length(word_key) between 1 and 120),
  word_type text,
  definition_kr text,
  video_id text,
  video_title text,
  channel_name text,
  created_at timestamptz not null default now(),
  unique (user_id, word_key)
);

create index if not exists saved_words_user_created_idx
  on public.saved_words (user_id, created_at desc);

alter table public.saved_words enable row level security;

create policy "Users can read their saved words"
  on public.saved_words for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their saved words"
  on public.saved_words for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their saved words"
  on public.saved_words for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their saved words"
  on public.saved_words for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.saved_sentences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sentence_key text not null check (char_length(sentence_key) between 1 and 240),
  sentence_text text not null check (char_length(sentence_text) between 1 and 5000),
  video_id text,
  video_title text,
  channel_name text,
  timestamp_sec double precision not null default 0,
  timestamp_display text not null default '00:00',
  created_at timestamptz not null default now(),
  unique (user_id, sentence_key)
);

create index if not exists saved_sentences_user_created_idx
  on public.saved_sentences (user_id, created_at desc);

alter table public.saved_sentences enable row level security;

create policy "Users can read their saved sentences"
  on public.saved_sentences for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their saved sentences"
  on public.saved_sentences for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their saved sentences"
  on public.saved_sentences for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their saved sentences"
  on public.saved_sentences for delete
  to authenticated
  using ((select auth.uid()) = user_id);
