create table if not exists public.episode_translations (
  id bigint generated by default as identity primary key,
  video_id text not null check (char_length(video_id) = 11),
  transcript_hash text not null check (char_length(transcript_hash) between 8 and 128),
  translation_version text not null check (char_length(translation_version) between 1 and 80),
  sentence_index integer not null check (sentence_index >= 0),
  source_text_hash text not null check (char_length(source_text_hash) between 8 and 128),
  translation_kr text not null check (char_length(translation_kr) between 1 and 10000),
  model text not null check (char_length(model) between 1 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (video_id, transcript_hash, translation_version, sentence_index)
);

create index if not exists episode_translations_cache_lookup_idx
  on public.episode_translations (
    video_id,
    transcript_hash,
    translation_version,
    sentence_index
  );

alter table public.episode_translations enable row level security;

revoke all on table public.episode_translations from anon, authenticated;
grant select, insert, update on table public.episode_translations to service_role;
grant usage, select on sequence public.episode_translations_id_seq to service_role;
